site_name: oligopipe
site_url: https://oligopipe.docs.com/
theme:
  name: mkdocs
  navigation_depth: 3
markdown_extensions:
  - toc:
      permalink: "#"
nav:
  - Input: input.md
  - Preprocessing:
    - Preprocessing pipeline: preprocess.md
    - Annotation database: database.md
  - Methods:
    - Prediction - VarCoPP: varcopp.md
    - Prioritization - HOP: hop.md
  - Results: results.md
  - FAQ: faq.md
  - About: about.md
validation:
  nav:
    omitted_files: ignore